package com.liferay.reestrRayonov.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Rayon service. Represents a row in the &quot;RR_Rayon&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.reestrRayonov.model.impl.RayonModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.reestrRayonov.model.impl.RayonImpl}.
 * </p>
 *
 * @author liza
 * @see Rayon
 * @see com.liferay.reestrRayonov.model.impl.RayonImpl
 * @see com.liferay.reestrRayonov.model.impl.RayonModelImpl
 * @generated
 */
public interface RayonModel extends BaseModel<Rayon> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a rayon model instance should use the {@link Rayon} interface instead.
     */

    /**
     * Returns the primary key of this rayon.
     *
     * @return the primary key of this rayon
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this rayon.
     *
     * @param primaryKey the primary key of this rayon
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the rayon ID of this rayon.
     *
     * @return the rayon ID of this rayon
     */
    public long getRayonId();

    /**
     * Sets the rayon ID of this rayon.
     *
     * @param rayonId the rayon ID of this rayon
     */
    public void setRayonId(long rayonId);

    /**
     * Returns the name of this rayon.
     *
     * @return the name of this rayon
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this rayon.
     *
     * @param name the name of this rayon
     */
    public void setName(String name);

    /**
     * Returns the kod of this rayon.
     *
     * @return the kod of this rayon
     */
    public int getKod();

    /**
     * Sets the kod of this rayon.
     *
     * @param kod the kod of this rayon
     */
    public void setKod(int kod);

    /**
     * Returns the archive of this rayon.
     *
     * @return the archive of this rayon
     */
    public boolean getArchive();

    /**
     * Returns <code>true</code> if this rayon is archive.
     *
     * @return <code>true</code> if this rayon is archive; <code>false</code> otherwise
     */
    public boolean isArchive();

    /**
     * Sets whether this rayon is archive.
     *
     * @param archive the archive of this rayon
     */
    public void setArchive(boolean archive);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.liferay.reestrRayonov.model.Rayon rayon);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.reestrRayonov.model.Rayon> toCacheModel();

    @Override
    public com.liferay.reestrRayonov.model.Rayon toEscapedModel();

    @Override
    public com.liferay.reestrRayonov.model.Rayon toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
