package com.liferay.reestrRayonov.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.reestrRayonov.model.Rayon;
import com.liferay.reestrRayonov.service.RayonService;
import com.liferay.reestrRayonov.service.persistence.RayonPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the rayon remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.reestrRayonov.service.impl.RayonServiceImpl}.
 * </p>
 *
 * @author liza
 * @see com.liferay.reestrRayonov.service.impl.RayonServiceImpl
 * @see com.liferay.reestrRayonov.service.RayonServiceUtil
 * @generated
 */
public abstract class RayonServiceBaseImpl extends BaseServiceImpl
    implements RayonService, IdentifiableBean {
    @BeanReference(type = com.liferay.reestrRayonov.service.RayonLocalService.class)
    protected com.liferay.reestrRayonov.service.RayonLocalService rayonLocalService;
    @BeanReference(type = com.liferay.reestrRayonov.service.RayonService.class)
    protected com.liferay.reestrRayonov.service.RayonService rayonService;
    @BeanReference(type = RayonPersistence.class)
    protected RayonPersistence rayonPersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private RayonServiceClpInvoker _clpInvoker = new RayonServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.liferay.reestrRayonov.service.RayonServiceUtil} to access the rayon remote service.
     */

    /**
     * Returns the rayon local service.
     *
     * @return the rayon local service
     */
    public com.liferay.reestrRayonov.service.RayonLocalService getRayonLocalService() {
        return rayonLocalService;
    }

    /**
     * Sets the rayon local service.
     *
     * @param rayonLocalService the rayon local service
     */
    public void setRayonLocalService(
        com.liferay.reestrRayonov.service.RayonLocalService rayonLocalService) {
        this.rayonLocalService = rayonLocalService;
    }

    /**
     * Returns the rayon remote service.
     *
     * @return the rayon remote service
     */
    public com.liferay.reestrRayonov.service.RayonService getRayonService() {
        return rayonService;
    }

    /**
     * Sets the rayon remote service.
     *
     * @param rayonService the rayon remote service
     */
    public void setRayonService(
        com.liferay.reestrRayonov.service.RayonService rayonService) {
        this.rayonService = rayonService;
    }

    /**
     * Returns the rayon persistence.
     *
     * @return the rayon persistence
     */
    public RayonPersistence getRayonPersistence() {
        return rayonPersistence;
    }

    /**
     * Sets the rayon persistence.
     *
     * @param rayonPersistence the rayon persistence
     */
    public void setRayonPersistence(RayonPersistence rayonPersistence) {
        this.rayonPersistence = rayonPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Rayon.class;
    }

    protected String getModelClassName() {
        return Rayon.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = rayonPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
